/* eslint-disable max-len */
export const CONTENT_TEXT = {
	Impact: [
		"Each person will be left with different intakes, but It often triggers curiosity about these torture camps and if they still exist.",
		"On Steam, this experience has 147 highly positive reviews; some compare it with the lives of the reviewers’ grandparents, and others mention how it affected them deeply.",
		"It shows the LGBT community as perceived across cultures. At the end of the experience, participants are faced with the unfair choice given to the protagonists: love or home. ",
		"It brings awareness of racial injustice and the ongoing struggle for Civil Rights in America. The historical footage inside the VR environment legitimizes the historical context magnifying its impact.",
		"The participant embodies a computer-generated 3D model of a Black man. Photo-realistic uncanniness prevents full engagement and enjoyment.",
		"Participants become aware of the possibility of losing their assets and how they would be treated if unhoused.",
	],
	Emotion: [
		"High-contrast lighting with abundant darkness, lack of color, and expressive narration convey negative emotions; the detainees’ bonding and friendship trigger tenderness and ",
		"This experience conveys the heartfelt author’s personal family narrative. Half of the 147 reviews on Steam praise the protagonists’ heroism or express they felt empathy.",
		"Narration and images of the personal narrative of two LGBTQ women unfold through their emotional closeness, fostering empathy and connection with the participant.",
		"The goal is to recreate the tension and drama of Martin Luther King’s assassination. Historical footage heightens the emotional charge.",
		"Embodiment in the victim’s body is intended to trigger emotions in a crescendo until a dramatic police encounter at the end of the experience, which triggers fear and uncertainty.",
		"The entire experience conveys a negative emotional charge, escalating to the bus scene, which triggers extreme anxiety.",
	],
	Interactivity: [
		"The experience does not employ interactive strategies, rendering the participant a spectator and mimicking the detainees’ lack of choices.",
		"To progress through the experience, the participant interacts with 3D assets and moves in space, holding a high level of agency.",
		"The participant is prompted to write words in Arabic in between chapters of the protagonists’ journey to progress through the experience, ",
		"The participant has to pick up props to progress through the events, even though no strategy indicates which items need interaction.",
		"Participants can move their limbs, such as waving in front of a mirror, and pick up or throw items.",
		"The participant can point at items and move their hands through space.",
	],
	Embodiment: [
		"This experience does not show hands or an avatar to trigger embodiment; the participant is inside the camp with the detainees, feeling like one of them.",
		"The participant feels like embodying one of the actors on a theater performance’s stage, interacting with assets and helping the protagonists in various tasks. ",
		"Like a spectator, the participant watches the two protagonists move through their difficult journey. The engaging visuals and environments trigger the sense of presence.",
		"Black hands, which contribute to triggering embodiment, are the only element signifying that a participant is a Black person. ",
		"The participants, embodying a Black man, Mike Sterling, pose in front of a mirror several times, seeing themselves reflected as Mike, a child at first, and an adult by the end.",
		"The participant embodies an individual who loses employment and shelter. Embodiment is employed as a strategy to trigger empathy toward unhoused individuals.",
	],
	Flow: [
		"The experience is visually and narratively cohesive due to its artistic visualizations and continuous narration. The only interruption is a scene of a detainee singing in the ",
		"As in a theater, artistic visual props and backdrops move in and out of view while spotlights guide the participant’s eye. These elements create a cohesive narrative flow.",
		"Even though visuals are diverse, alternating 2D and 3D, the thematically relevant interactive transition of writing in Arabic creates an episodic and cohesive narrative flow.",
		"The narrative is linear, but unclear interactive elements halt the action breaking the flow of events.",
		"Episodic narrative, with a mirror and voice, prompts to instill embodiment at every phase of the main character’s life.",
		"Different scenes and events appear through fade-in/out effects, transitioning participants through time and space.",
	],
	Cognition: [
		"Given that these camps are secret, the immersive visualization from hours of narration by three detainees is a precious opportunity for knowledge. ",
		"Multiple levels of learning unfold through the protagonist’s narrative, the Japanese cultural context, and the depiction of WWII internment camps.",
		"Multiple levels of learning unfold through the protagonists’ personal narrative, their cultural context, the countries they visit, and their writing in Arabic. ",
		"This historical documentary sheds light on the events, cultural context, and mood leading to Martin Luther King’s assassination.",
		"The focus should be the daily unfairness of living with racism and microaggressions, but the fear-inducing final scene can turn the participant toward concerns for their safety.",
		"Participants learn the feeling of becoming unhoused, losing their sense of safety and familiar belongings.",
	],
	Enjoyment: [
		"Art-based animated visuals, dynamic point of view, passionate narration, and singing make this experience lively and exciting, even in disclosing injustice.",
		"Art-based visuals, bright colors, well-designed lighting, and high agency make this experience lively and exciting. Steam features 147 highly positive reviews.",
		"Art-based visuals, colors, lighting, narration, and agency make this experience lively and exciting.",
		"The experience is enjoyable, with occasional annoyance when searching the interactive elements to progress through the events.",
		"The disconnect between the video footage environments and secondary characters and the computer-generated 3D models prevents full enjoyment.",
		"Photo-realistic scenes are anxiety-inducing, which at times renders the experience unpleasant.",
	],
	Time: [
		"This experience includes the narration and depiction of events that occurred in the past. One scene occurs in the mind of the narrators. Present, past, and imaginary time coexist.",
		"The narration is in the present, recalling the main character’s story, which is in the past. Historical photos of the actual protagonists add a wonderful dimension to the story.",
		"Time is episodic, alternating the protagonists’ narration with action through chapters that the participant unlocks to continue into the immersive rendition of the protagonists’ voice recordings and story.",
		"The narrative depicts the past. Historical footage of that time is intermixed with 3D computer-generated immersive worlds, contributing to describing that era and crucial moment in history. ",
		"The narrative is episodic, progressing through the life of a Black man from childhood to adulthood.",
		"The narrative is episodic, depicting a middle-class person’s transition to houselessness. Each chapter shows a decline and loss of a sense of safety and worldly belongings.",
	],
	Scale: [
		"Scale manipulation is used to show how armed guards dwarf the detainees’ bodies and to magnify a detainee who sings in an imagined grassland, symbolizing the longing for freedom.",
		"The guards are scaled up and inexpressive to represent a faceless and crushing government. The characters are scaled down to show they are fragile and powerless.",
		"Sometimes environments are scaled up to render the protagonists small and fragile. When the protagonists escape injustice, their heads are scaled up to fill the sky, celebrating their bond. ",
		"Scale is photo-realistic. All scenes are designed to mimic precisely real interior spaces, people, streets, parking lots, and buildings in the city.",
		"Scale is photo-realistic. All scenes are designed to mimic precisely real interior spaces, people, streets, and buildings in the city.",
		"Scale is aimed at photo-realism. All scenes are designed to mimic precisely real interior spaces, people, streets, and buildings in the city.",
	],
	Space: [
		"Scenes within the prison are crowded, invoking feelings of claustrophobia and helplessness. In contrast, scenes of the imagined open field invoke a calm sense of hope.",
		"The space is designed to make the participant feel, at times, like on a theatrical stage or in tight spaces (i.e., train cart), and sometimes in the vast outdoors.",
		"Space triggers emotions. The vast, dark, and intimidating forest and immigration building trigger fear; the quaint couch where the protagonist talk invoke safety and calmness.",
		"Space is not manipulated to convey emotions or emphasize ideas. Environments are meant to look realistic.",
		"Participants are kept far from other characters. People and environments are photo-realistic and intentionally neutral in color and appearance.",
		"Environments are photo-realistic with no spatial manipulation to convey emotions or emphasize concepts or ideas. ",
	],
	"Point of View": [
		"The point of view changes from a bird’s eye, to eye-level with other detainees, to a worm’s eye view with guards and doctors.",
		"The point of view comprises what an actor could see on a theater stage with props, objects, and environments, changing drastically around the participant, who’s part of the protagonist’s story.  ",
		"2D eye-level hand-drawn peaceful environments alternate with 3D crowded scenes. The participant floating on a platform above the city to reach the protagonists preparing for their escape is compelling and unique.",
		"The participants’ point of view varies with their whereabouts through the city and interiors as a character living the day of Martin Luther King’s assassination.",
		"A recurring point of view is when the participant has to stand in front of a mirror to identify with the Black man in it. Often, the participant is looked down on by other characters.",
		"The participants see their hands, their belongings disappearing from their apartment and then are forced to keep their eyes on a backpack containing their life’s basic needs.",
	],
	"Visuals/Sound": [
		"Using black and white creates high contrast harshness, which is used to draw the participant’s attention. The main characters’ somber music and narration convey sadness and despair.",
		"Light particles guide the participant toward important visuals while the author of the experience and narrator, Randall, tells the story, engaging the participant with his great-grandfather’s story.",
		"Color guides the participant’s eye toward essential elements in the narrative while the protagonists’ voices describe their feelings and recount their journey as the participant witnesses it in VR. ",
		"Stylized 3D-colored environments and characters alternate with 2D historical black and white footage ambient noise (cars, sirens, radio, etc.) add to the experience’s realism.",
		"Photo-realistic environments and secondary characters seem to be video footage with added 3D prompts. Ambient noise or voice prompts are sparse, and no narration or music exists.",
		"Photo-realistic representation is enhanced with graphics to signify props for interactions. Voice prompts guide participants, who can choose to hear stories of unhoused bus riders narrating their life story.",
	],
} as const;

export const CONTENT_IMAGE_FOLDERS = [
	"12_sensory_visuals-sound",
	"11_sensory_point-of-view",
	"10_sensory_space",
	"09_sensory_scale",
	"08_sensory_time",
	"07_psychological_enjoyment",
	"06_psychological_cognition",
	"05_psychological_flow",
	"04_psychological_embodiment",
	"03_psychological_interactivity",
	"02_psychological_emotion",
	"01_psychological_impact",
] as const;

export const CONTENT_IMAGE_NAMES = ["reeducated.jpg", "book-of-distance.jpg", "another-dream.jpg", "i-am-a-man.jpg", "1000-cut-journey.jpg", "becoming-homeless.jpg"] as const;

export const EXPERIENCES_STATS = [
	// [0, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10],
	[7.69, 7.72, 2.75, 4.83, 7.81, 8.42, 8.03, 7.61, 7.72, 8.33, 8.36, 8.17],
	[7.23, 8.57, 8.57, 8.27, 7.07, 9.0, 7.83, 8.87, 8.7, 8.47, 8.97, 8.67, 8.57],
	[6.82, 6.9, 5.8, 4.53, 7.17, 7.21, 7.4, 6.87, 7.6, 7.32, 7.86, 7.7],
	[6.59, 7.35, 5.71, 6.68, 7.53, 6.62, 6.94, 7.82, 8.24, 7.29, 6.88, 6.5],
	[7.61, 7.23, 7.03, 7.0, 8.3, 6.63, 7.03, 8.2, 7.73, 6.2, 8.13, 7.41],
	[7.57, 8.14, 7.71, 8.29, 8.25, 6.32, 6.89, 7.97, 8.43, 8.64, 8.43, 7.71],
] as const;
