/* eslint-disable max-len */
export const CONTENT_TEXT = {
	Impact: [
		"It exposes places of brainwashing, torture, and punishment secretly held in China. The end of it makes us wonder if these camps still exist, instilling curiosity.",
		"This experience has 147 very positive reviews on Steam. Many reviewers make parallels with the lives of their own grandparents, others mention how it affected them deeply.",
		"This experience depicts how the LGBT community is perceived across different cultures and the protagonists' journey. At the end of the experience, the participant is placed in the protagonists' shoes when asked to choose between love and home.",
		"It features modern injustice due to racism and the ongoing struggle for Civil Rights in America. The historical footage inside the VR environment legitimizes the historical context rendering this piece very impactful.",
		"The participant embodies a CGI model of a Black individual. Photorealistic uncanniness prevents full engagement.",
		"Participants become aware of the possibility of losing their assets and how they would be treated if unhoused.",
	],
	Emotion: [
		"The hand-drawn visuals, high-contrast lighting, lack of color, and expressive narration aim to convey emotions through the protagonists' friendship, bonding, and powerlessness in front of injustice.",
		"This experience conveys the heartfelt author's personal family narrative. Half of the 147 reviews on Steam praise the protagonists’ heroism or point to feeling empathy.",
		"Narration and images of the personal narrative of two LGBTQ women unfold through their emotional closeness, fostering empathy and connection with the participant.",
		"This historical documentary immerses the participant in the drama of a moment in history. Historical footage heightens emotional engagement.",
		"Embodiment in the victim's body is intended to trigger emotions in a crescendo until a police encounter at the end.",
		"Embodiment in the victim's body is intended to trigger emotions. The bus scene triggers anxiety.",
	],
	Interactivity: [
		"This experience does not employ interactive strategies. Just like the detainees, the participant has no freedom to act.",
		"To progress through the experience the participant interacts with 3D assets, moves in space, holding a high level of agency.",
		"To progress through the experience the participant is prompted to write words in Arabic in between chapters of the protagonists' journey.",
		"To progress through the experience the participant picks up objects in the various scenes, such as newspapers and other props.",
		"Participants can move their arms, such as when they wave in front of a mirror, and pick up or throw items.",
		"The participant points at items and can move their hands through space.",
	],
	Embodiment: [
		"While observing the detainees' experience as spectators, lack of agency contributes to feeling as one of them.",
		"The participant might embody one of the actors on a theater performance's stage, interacting with assets and helping the protagonists in various tasks.",
		"The participant feels like participating to the the protagonists' journey as a spectator.",
		"The participant is supposed to embody a Black person, shown by the Black hands attached to the controllers.",
		"The participant, which is supposed to embody a Black individual, Mike Sterling, poses in front of a mirror several times and sees a black person, first as a child,later as an adult.",
		"The participant is supposed to embody an individual who loses employment and shelter. Embodiment is employed as a strategy to trigger empathy toward unhoused individuals.",
	],
	Flow: [
		"The experience is visually and narratively cohesive due to its artistic visualizations and continuous narration of past experiences.",
		"As in a theater, art-based visual props and backdrops move in and out of view, while spotlights help guide the participant's eye in each setup. These elements drive a cohesive narrative flow.",
		"The thematically relevant interactive scene transition of writing in Arabic creates an episodic and cohesive narrative flow.",
		"CGI 3D worlds and 2D video footage alternate to depict historical moments, causing a more erratic flow. Interactive elements are not evident, causing halts in the story that prevent a smooth flow.",
		"Episodic narrative flow unfolds, with a mirror and a narrator prompting the participant to wave to instill embodiment.",
		"Different scenes and events appear through fade-in/out transitions, transitioning participants through time and space.",
	],
	Cognition: [
		"It teaches about life inside reeducation camps with a glimpse of the detainees' personal lives before detention.",
		"Multiple levels of learning unfold through the protagonist's personal narrative, the Japanese cultural context, and the depiction of WWII internment camps.",
		"Multiple levels of learning unfold through the protagonists' personal narrative, their cultural context, the countries they visit, and the writing in Arabic language.",
		"It focuses on the history of the Civil Rights Movement in the U.S. Historical photos and videos convey well the historical context.",
		"The focus is the daily unfairness of living with racism and microaggressions.",
		"Participants learn how it feels to become unhoused.",
	],
	Enjoyment: [
		"Art-based animated 2D visuals, lighting, dynamic point of view, and beautiful narration and singing make this experience lively and exciting.",
		"Art-based visuals, colors, lighting, and agency make this experience lively and exciting. On Steam, 147 reviews are very positive.",
		"Art-based visuals, colors, lighting, narration, and agency make this experience lively and exciting.",
		"The fact that it's challenging to determine interactive elements detracts from the overall enjoyment of the experience.",
		"Photorealism and the use of video mixed with 3d cgi can signal a lack of cohesiveness that detracts from the enjoyment.",
		"Photorealistic Interactive elements are  anxiety-inducing, which is the intention of the experience, but renders it unpleasant.",
	],
	Time: [
		"This experience includes today's narration and depiction of events that occurred in the past. One scene occurs in the mind of the narrators. Present, past, and imaginary time coexist.",
		"The narrator exists in the present day, and also with the characters within the story who live in the past. As in a theatrical performance, the participant experiences the past but acts in the present.",
		"The experience feels as if it is occurring in the present, even though it is based on the protagonists' recollections of the recent past.",
		"The narrative occurs in the past. The characters exist in the same place in time, experiencing a linear narrative. Historical footage of that time is intermixed with the 3D computer-generated immersive worlds, contributing to describing that era and crucial moment in history.",
		"The narrative has distinct segments representing the main character's life periods. The segments are not historical events, and they exist in the present, as the participant follows the main character's life. The timeline in this experience is linear and episodic, divided into phases representing the protagonist’s ages from childhood to adulthood.",
		"The experience has distinct segments that represent different events in the main character's (or participant’s) life. The segments do not depict historical events; they exist in the present. The timeline in this experience is linear and episodic.",
	],
	Scale: [
		"Scale manipulation is used to show how armed guards dwarf the detainees' bodies and to celebrate a detainee who sings in an imagined grassland, symbolizing their deep longing for freedom.",
		"The figures representing the government institution is scaled up to represent how faceless and powerful that institution is. The characters are scaled down to show that they are at the mercy of a larger force.",
		"In the scene that takes place in the government building, when being processed for immigration, the interior of the building is scaled up to unrealistic proportions, rendering the characters small and helpless. In a later scene, the heads of the main characters are scaled up to fill the sky. They rest against each other, showing that they are strong (big) thanks to the love they feel.",
		"The participant enters the experience facing a wall made of historical photos, scaled up to be very large and arranged neatly so that the participant can observe them and get an idea of the narrative. Beyond this opening, the experience does not manipulate scale purposefully or meaningfully. All scenes are designed to look realistic; no artistic liberties were taken and scaled as in the real interior spaces and city at that time in history.",
		"This experience does not employ scale in any purposeful or meaningful way. All scenes are designed to look realistic, so no artistic liberties were taken in manipulating the scale of virtual objects or environments.",
		"This experience does not employ scale purposefully or meaningfully. All scenes are designed to look realistic, so no artistic liberties were taken in manipulating the scale of virtual objects or environments.",
	],
	Space: [
		"Scenes within the prison are crowded, invoking feelings of claustrophobia and helplessness. In contrast, scenes of the imagined open field invoke feelings of hope.",
		"The spatial design varies from scene to scene. In some scenes, there is much physical distance between characters (i.e., when Randall's grandfather initially arrives to Canada on a boat and sees his wife). In others, buildings and interactive objects are within close reach of the participant.",
		"When being processed in the government building, the characters are far away from the participant, which helps perceive them as small, and fragile, in an unfamiliar and unknown world. Another scene of space conveying fear is when they cross a forest or when the participant “floats” on a square to reach the apartment in which they are packing to leave their country and loved ones. The transition from the large open space to a small room is a zoom into their painful departure.",
		"Environments in this experience are meant to look realistic. The sense of space is not manipulated to convey emotions or emphasize ideas.",
		"Characters stay far from the main protagonist and the participant's avatar. Spaces are photorealistic and intentionally neutral.",
		"Environments are photo-realistic with no spatial manipulation or artistic strategies to convey emotions or emphasize ideas.",
	],
	"Point of View": [
		"The point of view of the participant changes from scene to scene. In some scenes, the participant takes on a bird's eye view, witnessing everything from above. In other scenes, they take on a worm's eye view, looking up at whatever is above them.",
		"This experience is designed to mimic a theater stage. So, the point of view is limited to what an audience member or actor could reasonably see. While objects and environments change drastically, the point of view is not heavily manipulated. The participant views and follows the characters as if it’s part of the story, helping the protagonists during key moments (i.e.packing for trips) and reaching accomplishments (i.e., planting at the farm).",
		"The point of view alternates from 2D scenes (where the women talk) to 3D environments (where they act and move toward freedon). In one scene, the participants are placed on a platform high above the ground, allowing them to see the city below them. Toward the end of the experience, the player watches as the two characters join hands and walk over the participant's head, giving the illusion the player is low to the ground.",
		"Environments in this experience are meant to look realistic. The point of view is not manipulated to convey emotions or emphasize ideas.",
		"The environments are meant to look photo-realistic. In the scenes in which the participant is standing in front of the mirror, the point of view is controlled and manipulated to trigger identification with a black person.",
		"Environments are photo-realistic with no point-of-view manipulation or artistic strategies to convey emotions or emphasize ideas.",
	],
	"Visuals/Sound": [
		"See: The use of black and white scenes creates high contrast in the images, which is used to help draw the participant's attention toward important scenes. Hear: The somber music and narration by the main characters sets the tone for the rest of the experience.",
		"See: Spot lights and light particles guide the participant toward important visuals. Hear: The author of the experience and narrator, Randall, tells the story, prompts the interaction with certain objects, and asks questions to the participants, further engaging them in his great-grandfather’s story.",
		"See: Color guides the participant's eye toward essential elements in the narrative. The words “I chose” and “light”, for example, are brightly colored and stand out. Hear: The main characters’ voices describe their feelings and recount their journey as the participant witnesses it in VR.",
		"See: Large historical photographs stand out against the black background. 3D characters are stylized in contrast with the 2D historical footage, which is very realistic. Hear: Environments have ambient noise, adding to realism. For example, in the protest scenes, the participant can hear cars, sirens, the radio, and other background noises.",
		"See: This experience employs realism and instill a sense of embodiment through the use of a mirror which is supposed to make the participant believe they are a black person. In between scenes, participants look at their avatar in a mirror as they listen to voice prompts. The body of the avatar is a 3D computer model, the other characters are video-based. Hear: Ambient noise or voice prompts only, no non-diegetic sounds or music exist.",
		"See: Environments and Characters are photo-realistic. Hear: The participant can select different audio recordings from unhoused bus riders narrating their life story.",
	],
} as const;

export const CONTENT_IMAGE_FOLDERS = [
	"12_sensory_visuals-sound",
	"11_sensory_point-of-view",
	"10_sensory_space",
	"09_sensory_scale",
	"08_sensory_time",
	"07_psychological_enjoyment",
	"06_psychological_cognition",
	"05_psychological_flow",
	"04_psychological_embodiment",
	"03_psychological_interactivity",
	"02_psychological_emotion",
	"01_psychological_impact",
] as const;

export const CONTENT_IMAGE_NAMES = ["reeducated.png", "book-of-distance.png", "another-dream.png", "i-am-a-man.png", "1000-cut-journey.png", "becoming-homeless.png"] as const;

export const EXPERIENCES_STATS = [
	// [0, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10],
	[7.69, 7.72, 2.75, 4.83, 7.81, 8.42, 8.03, 7.61, 7.72, 8.33, 8.36, 8.17],
	[7.23, 8.57, 8.57, 8.27, 7.07, 9.0, 7.83, 8.87, 8.7, 8.47, 8.97, 8.67, 8.57],
	[6.82, 6.9, 5.8, 4.53, 7.17, 7.21, 7.4, 6.87, 7.6, 7.32, 7.86, 7.7],
	[6.59, 7.35, 5.71, 6.68, 7.53, 6.62, 6.94, 7.82, 8.24, 7.29, 6.88, 6.5],
	[7.61, 7.23, 7.03, 7.0, 8.3, 6.63, 7.03, 8.2, 7.73, 6.2, 8.13, 7.41],
	[7.57, 8.14, 7.71, 8.29, 8.25, 6.32, 6.89, 7.97, 8.43, 8.64, 8.43, 7.71],
] as const;
